### ISSUE TITLE
refactor(graphql): extract graphql() logic into graphql$UCCF to suppo…

### ISSUE THREAD

**Issue by ajagnanan1** [ajagnanan1/resto-1#250]
#649 Issue by __xareelee__

**This PR is for discussion only, not for real merge.**

This PR demonstrates how to convert a Promise-based function to a reactive-callback-based function to support all kinds of async handling system without any new dependency.

We use `promisify()` to turn it back to a Promise-based function for the default flavor. 

It currently is not **reactive** yet due to the upstream functions are not reactive (as Promise). We need to refactor all upstream functions to be reactive-callback-based.

More discussions on #647.

## TODO

- [x] make first refactor demo and pass the tests and lint.
- [ ] add strict Flow type and pass the type check.
- [ ] refactor the upstream functions of graphql to be reactive-callback-based (UCC functions) until it fully supports reactive programming.

For more info on UCC functions, please refer to [this article](https://gist.github.com/xareelee/e85c8b2134ff1805ab1ab2f1c8a037ce).
